import * as THREE from 'three';
import { tween, ease, damp } from './motion.js';

/**
 * CH 1 is real footage; CH 2–7 are placeholder programmes of a fictional
 * Indonesian station (TVSN) generated by tools/make_channels.py.
 * `fit`: 0 fills the tube (crops a wide picture's sides), 1 letterboxes it whole.
 * `subtitles`: optional WebVTT file, shown as pop-up captions under the TV.
 * `restart`: start from 0:00 on every tune-in (default: join the "live" loop).
 */
export const CHANNELS = [
  { num: 1, src: 'videos/ch1.mp4', name: 'FILM ANIMASI', fit: 0.5, subtitles: 'subtitles/ch1.id.vtt', restart: true },
  { num: 2, src: 'videos/ch2.mp4', name: 'BERITA MALAM' },
  { num: 3, src: 'videos/ch3.mp4', name: 'PRAKIRAAN CUACA' },
  { num: 4, src: 'videos/ch4.mp4', name: 'PENUTUP SIARAN' },
  { num: 5, src: 'videos/ch5.mp4', name: 'WAYANG KULIT SEMALAM SURI' },
  { num: 6, src: 'videos/ch6.mp4', name: 'KAMERA PANTAU KRAKATAU' },
  { num: 7, src: 'videos/ch7.mp4', name: 'TVSN · GANGGUAN TEKNIS' },
];
const MAX_CH = 9;

/** minimal WebVTT reader: [{ start, end, text }] in seconds */
function parseVTT(src) {
  const time = (s) => s.trim().split(':').reduce((acc, part) => acc * 60 + parseFloat(part), 0);
  const cues = [];
  for (const block of src.replace(/\r/g, '').split(/\n{2,}/)) {
    const lines = block.split('\n');
    const at = lines.findIndex((l) => l.includes('-->'));
    if (at < 0) continue;
    const [a, b] = lines[at].split('-->');
    cues.push({ start: time(a), end: time(b.trim().split(/\s+/)[0]), text: lines.slice(at + 1).join('\n').trim() });
  }
  return cues;
}

// The TV_Screen mesh's UVs cover exactly the glass area of screen.png.
// (u0, v0, width, height) in glTF UV space, where v grows downward.
const GLASS = new THREE.Vector4(0.0196, 0.1299, 0.9607, 0.7714);
const OSD_W = 1024;
const OSD_H = 828; // glass aspect ≈ 1.237

const vertexShader = /* glsl */ `
  varying vec2 vUv;
  void main() { vUv = uv; gl_Position = vec4(position.xy, 0.0, 1.0); }
`;

const fragmentShader = /* glsl */ `
  precision highp float;
  uniform sampler2D tVideo;
  uniform sampler2D tOSD;
  uniform vec4 uGlass;
  uniform float uTime, uStatic, uHasVideo, uGlitch, uRoll, uBand, uBright;
  uniform float uScaleX, uScaleY, uDot, uOn, uVideoAspect, uFlipX, uFit, uGain;
  varying vec2 vUv;

  float h11(float p) { p = fract(p * 0.1031); p *= p + 33.33; p *= p + p; return fract(p); }
  float h21(vec2 p) { vec3 p3 = fract(vec3(p.xyx) * 0.1031); p3 += dot(p3, p3.yzx + 33.33); return fract((p3.x + p3.y) * p3.z); }
  float vnoise(float x) { float i = floor(x); float f = fract(x); return mix(h11(i), h11(i + 1.0), f * f * (3.0 - 2.0 * f)); }

  const float ASPECT = 1.237;

  vec3 picture(vec2 p) {                       // p: 0..1, y down
    vec3 c = vec3(0.0);
    if (uHasVideo > 0.5) {
      // displayed picture size in tube units: cover (uFit 0) → contain (uFit 1)
      float rel = uVideoAspect / ASPECT;
      float s = mix(max(1.0, 1.0 / rel), min(1.0, 1.0 / rel), uFit);
      vec2 v = (p - 0.5) / vec2(rel * s, s) + 0.5;
      if (all(greaterThan(v, vec2(0.0))) && all(lessThan(v, vec2(1.0)))) c = texture2D(tVideo, vec2(v.x, 1.0 - v.y)).rgb;
    }
    vec4 o = texture2D(tOSD, vec2(p.x, 1.0 - p.y));
    return mix(c, o.rgb, o.a);
  }

  void main() {
    vec2 g = (vUv - uGlass.xy) / uGlass.zw;    // 0..1 across the glass, y down
    if (uFlipX > 0.5) g.x = 1.0 - g.x;
    vec2 cc = g - 0.5;
    float r2 = dot(cc, cc);

    // tube bulge: the picture bows outward and loses its corners
    vec2 p = 0.5 + cc * (1.0 + r2 * 0.24) * 0.955;
    // power on / off: beam squashes to a line, then a dot
    p = 0.5 + (p - 0.5) / vec2(max(uScaleX, 1e-3), max(uScaleY, 1e-3));
    float inside = step(0.0, p.x) * step(p.x, 1.0) * step(0.0, p.y) * step(p.y, 1.0);

    float t = uTime;
    float line = floor(p.y * 240.0);
    float jitter = h11(line + floor(t * 30.0) * 7.13) - 0.5;
    float tear = step(1.0 - 0.07 * uGlitch, h11(floor(p.y * 26.0) + floor(t * 14.0) * 3.7));
    p.x += jitter * (0.0010 + 0.006 * uGlitch) + tear * (h11(line) - 0.5) * 0.14 * uGlitch;
    p.x += sin(p.y * 22.0 + t * 2.7) * 0.0010 * (1.0 + 3.0 * uGlitch);

    float band = smoothstep(0.07, 0.0, abs(p.y - fract(t * 0.23))) * uBand;   // tracking error
    p.x += band * 0.022 * sin(p.y * 180.0 + t * 40.0);
    p.y = fract(p.y + uRoll);                                                   // vertical hold

    float ca = 0.0014 + 0.005 * uGlitch + band * 0.005 + r2 * 0.008;           // RGB separation
    vec3 col = vec3(picture(p + vec2(ca, 0.0)).r, picture(p).g, picture(p - vec2(ca, 0.0)).b);

    // analog snow (the OSD stays readable over it)
    float frame = floor(t * 50.0);
    float sn = h21(floor(vec2(p.x * 380.0, p.y * 290.0)) + frame * vec2(17.0, 31.0));
    float streak = h11(floor(p.y * 290.0) * 1.7 + frame);
    float snow = pow(mix(sn, sn * streak * 1.6, 0.4), 1.35) * 1.2;
    vec4 osd = texture2D(tOSD, vec2(p.x, 1.0 - p.y));
    col = mix(col, mix(vec3(snow), osd.rgb, osd.a * 0.92), clamp(uStatic, 0.0, 1.0));
    col += (sn - 0.5) * 0.05 + band * 0.06;

    // scanlines + aperture grille
    col *= 0.74 + 0.26 * (0.5 + 0.5 * cos(p.y * 6.2831853 * 240.0));
    col *= (0.82 + 0.18 * cos(6.2831853 * (vec3(g.x * 330.0) - vec3(0.0, 0.3333, 0.6667)))) * 1.12;

    // flicker
    col *= 0.965 + 0.035 * sin(t * 113.0) + (vnoise(t * 7.0) - 0.5) * 0.06;

    // automatic brightness limiter (set from the average picture level) + soft
    // highlight shoulder, so white scenes keep their detail instead of blowing out
    col *= uGain;
    vec3 over = max(col - 0.7, 0.0);
    col = col - over + over / (1.0 + over * 2.2);
    col *= min(1.0 / max(uScaleY, 0.15), 3.0) * inside * uOn * uBright;
    col += vec3(0.9, 0.95, 1.0) * uDot * exp(-length(cc * vec2(1.24, 1.0)) * 26.0) * 3.0;

    col *= mix(0.42, 1.0, 1.0 - smoothstep(0.30, 0.78, length(cc * vec2(1.0, 1.1))));
    vec2 d = max(abs(cc) * 2.0 - 0.88, 0.0);
    col *= 1.0 - smoothstep(0.09, 0.12, length(d));
    gl_FragColor = vec4(max(col, 0.0), 1.0);
  }
`;

const probeShader = /* glsl */ `
  precision highp float;
  uniform sampler2D tSrc;
  uniform vec4 uGlass;
  void main() {
    vec3 acc = vec3(0.0);
    for (int i = 0; i < 7; i++)
      for (int j = 0; j < 7; j++)
        acc += texture2D(tSrc, uGlass.xy + uGlass.zw * (vec2(float(i), float(j)) + 0.5) / 7.0).rgb;
    gl_FragColor = vec4(acc / 49.0, 1.0);
  }
`;

export class CRTScreen {
  constructor(renderer, screenMesh, audio) {
    this.renderer = renderer;
    this.audio = audio;
    this.mesh = screenMesh;

    this.rt = new THREE.WebGLRenderTarget(1024, 832, {
      depthBuffer: false,
      generateMipmaps: true,
      minFilter: THREE.LinearMipmapLinearFilter,
      magFilter: THREE.LinearFilter,
    });
    this.rt.texture.anisotropy = renderer.capabilities.getMaxAnisotropy();

    // on-screen display, drawn with a canvas and composited in the shader
    this.osd = document.createElement('canvas');
    this.osd.width = OSD_W;
    this.osd.height = OSD_H;
    this.osdCtx = this.osd.getContext('2d');
    this.osdTex = new THREE.CanvasTexture(this.osd);
    this.osdTex.colorSpace = THREE.SRGBColorSpace;
    this.osdSig = '';
    this.osdState = { chUntil: 0, volUntil: 0, msg: '', msgUntil: 0, infoUntil: 0 };

    const black = new THREE.DataTexture(new Uint8Array([0, 0, 0, 255]), 1, 1);
    black.needsUpdate = true;

    this.uniforms = {
      tVideo: { value: black },
      tOSD: { value: this.osdTex },
      uGlass: { value: GLASS },
      uTime: { value: 0 },
      uStatic: { value: 1 },
      uHasVideo: { value: 0 },
      uGlitch: { value: 0.2 },
      uRoll: { value: 0 },
      uBand: { value: 0 },
      uBright: { value: 1 },
      uScaleX: { value: 1 },
      uScaleY: { value: 1 },
      uDot: { value: 0 },
      uOn: { value: 1 },
      uVideoAspect: { value: 4 / 3 },
      uFlipX: { value: 0 },
      uFit: { value: 0 },
      uGain: { value: 1 },
    };
    this.quadCam = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);
    this.quad = new THREE.Mesh(
      new THREE.PlaneGeometry(2, 2),
      new THREE.ShaderMaterial({ uniforms: this.uniforms, vertexShader, fragmentShader, depthTest: false, depthWrite: false }),
    );
    this.quad.frustumCulled = false;

    // 1×1 average of the picture → drives the room light
    this.probeRT = new THREE.WebGLRenderTarget(1, 1, { depthBuffer: false });
    this.probe = new THREE.Mesh(
      new THREE.PlaneGeometry(2, 2),
      new THREE.ShaderMaterial({
        uniforms: { tSrc: { value: this.rt.texture }, uGlass: { value: GLASS } },
        vertexShader,
        fragmentShader: probeShader,
        depthTest: false,
        depthWrite: false,
      }),
    );
    this.probe.frustumCulled = false;
    this.probePx = new Uint8Array(4);
    this.lightColor = new THREE.Color(0.6, 0.65, 0.7);
    this.lightLevel = 0;
    this._target = new THREE.Color();
    this._frame = 0;

    // glass: keep the original smudged dark tube for reflections, emit the picture
    const old = screenMesh.material;
    this.material = new THREE.MeshStandardMaterial({
      map: old.map ?? null,
      color: 0x2e3130, // dark tube glass: a light base reads as a milky veil over the picture
      roughnessMap: old.roughnessMap ?? null,
      roughness: 1,
      metalness: 0,
      emissive: 0xffffff,
      emissiveMap: this.rt.texture,
      emissiveIntensity: 1.05,
      envMapIntensity: 2.4,
    });
    screenMesh.material = this.material;

    // channel sources
    this.videos = new Map();
    for (const ch of CHANNELS) {
      const v = document.createElement('video');
      v.src = ch.src;
      v.crossOrigin = 'anonymous';
      v.loop = true;
      v.muted = true;
      v.playsInline = true;
      v.preload = 'auto';
      const tex = new THREE.VideoTexture(v);
      tex.colorSpace = THREE.SRGBColorSpace;
      const entry = { video: v, tex, ch, cues: [] };
      if (ch.subtitles) {
        fetch(ch.subtitles).then((r) => r.text()).then((t) => { entry.cues = parseVTT(t); }).catch(() => {});
      }
      this.videos.set(ch.num, entry);
    }

    this.power = true;
    this.channel = 0; // 0 = AV input, no signal
    this.prevChannel = 1;
    this.volume = 12; // 0..20
    this.muted = false;
    this.current = null;
    this.hover = 0;
    this.fx = { kick: 0, glitch: 0.15, roll: 0, band: 0, nextEvent: 4 };
    this._pushAudio();
  }

  /** call inside a user gesture so later playback may carry sound */
  unlockMedia() {
    for (const { video } of this.videos.values()) {
      video.muted = false;
      video.play().then(() => { if (video !== this.current?.video) video.pause(); }).catch(() => {});
    }
  }

  get hasSignal() { return this.power && !!this.current && this.current.video.readyState >= 2; }
  get channelInfo() { return this.current?.ch ?? null; }

  /** subtitle line on screen right now, or '' */
  get subtitle() {
    if (!this.hasSignal || !this.current.cues.length || this.fx.kick > 0.3) return '';
    const t = this.current.video.currentTime;
    return this.current.cues.find((c) => t >= c.start && t < c.end)?.text ?? '';
  }

  // ------------------------------------------------------------ remote API
  press(label, half) {
    if (label === 'POWER') return this.togglePower();
    if (!this.power) return;
    if (/^\d$/.test(label)) return this.setChannel(Number(label));
    switch (label) {
      case 'CH': case 'UP': case 'DOWN': {
        const dir = label === 'UP' || (label === 'CH' && half > 0) ? 1 : -1;
        return this.setChannel((this.channel + dir + MAX_CH + 1) % (MAX_CH + 1));
      }
      case 'VOL': case 'RIGHT': case 'LEFT': {
        const dir = label === 'RIGHT' || (label === 'VOL' && half > 0) ? 1 : -1;
        this.volume = THREE.MathUtils.clamp(this.volume + dir * 2, 0, 20);
        this.muted = false;
        this.osdState.volUntil = performance.now() + 2200;
        return this._pushAudio();
      }
      case 'MUTE':
        this.muted = !this.muted;
        return this._pushAudio();
      case 'PREV':
        return this.setChannel(this.prevChannel);
      case 'INPUT':
        return this.setChannel(this.channel === 0 ? this.prevChannel || 1 : 0);
      case 'INFO': case 'OK':
        this.osdState.chUntil = this.osdState.infoUntil = performance.now() + 3500;
        return;
      default: {
        const text = { SLEEP: 'TIMER TIDUR  30', CC: 'TEKS  MATI', MODE: 'GAMBAR  CERAH', SAP: 'AUDIO  MONO', MENU: 'MENU TERKUNCI', BACK: 'KELUAR', FUNC: 'AFT  NYALA', DOT: '— —' }[label];
        this.flash(text ?? label);
      }
    }
  }

  flash(msg) {
    this.osdState.msg = msg;
    this.osdState.msgUntil = performance.now() + 1800;
  }

  setChannel(n) {
    if (!this.power) return;
    if (n === this.channel) {
      this.osdState.chUntil = performance.now() + 3000;
      if (this.current?.ch.restart) { // pressing it again replays from the start
        this.fx.kick = 0.8;
        this.fx.glitch = 0.8;
        this.audio.burst(0.3);
        clearTimeout(this._swap);
        this._swap = setTimeout(() => this._attach(this.current), 140);
      }
      return;
    }
    this.prevChannel = this.channel;
    this.channel = n;
    const fx = this.fx;
    fx.kick = 1;
    fx.glitch = 1;
    fx.roll = (0.25 + Math.random() * 0.55) * (Math.random() < 0.5 ? -1 : 1);
    this.osdState.chUntil = performance.now() + 3200;
    this.audio.burst(0.42 + Math.random() * 0.15);
    clearTimeout(this._swap);
    this._swap = setTimeout(() => this._attach(this.videos.get(n) ?? null), 140);
  }

  togglePower() {
    this.power ? this.powerOff() : this.powerOn();
  }

  powerOff() {
    if (!this.power) return;
    this.power = false;
    this.audio.powerOff();
    const u = this.uniforms;
    tween({ key: 'crt-power', duration: 0.16, easing: ease.outCubic, update: (e) => { u.uScaleY.value = THREE.MathUtils.lerp(1, 0.006, e); } })
      .then((done) => done && tween({ key: 'crt-power', duration: 0.2, easing: ease.outCubic, update: (e) => { u.uScaleX.value = 1 - e; u.uDot.value = e; } }))
      .then((done) => {
        if (!done) return;
        u.uOn.value = 0;
        this._attach(null);
        return tween({ key: 'crt-power', duration: 0.9, easing: ease.outQuart, update: (e) => { u.uDot.value = 1 - e; } });
      });
  }

  powerOn() {
    if (this.power) return;
    this.power = true;
    this.audio.powerOn();
    const u = this.uniforms;
    u.uOn.value = 1;
    u.uDot.value = 0;
    u.uScaleX.value = 0;
    u.uScaleY.value = 0.006;
    this.fx.kick = 1;
    this.fx.glitch = 0.8;
    this._attach(this.videos.get(this.channel) ?? null);
    this.osdState.chUntil = performance.now() + 3000;
    tween({ key: 'crt-power', duration: 0.12, easing: ease.outCubic, update: (e) => { u.uScaleX.value = e; } })
      .then((done) => done && tween({ key: 'crt-power', duration: 0.45, easing: ease.outQuart, update: (e) => { u.uScaleY.value = THREE.MathUtils.lerp(0.006, 1, e); } }));
    this._pushAudio();
  }

  _attach(entry) {
    for (const { video } of this.videos.values()) if (video !== entry?.video) video.pause();
    this.current = entry;
    if (!entry) return;
    const v = entry.video;
    if (entry.ch.restart) v.currentTime = 0;
    // otherwise tune in "live": the broadcast kept running while we were away
    else if (v.duration) v.currentTime = (performance.now() / 1000) % v.duration;
    v.play().catch(() => {});
    this.uniforms.tVideo.value = entry.tex;
    this.uniforms.uFit.value = entry.ch.fit ?? 0;
    if (v.videoWidth) this.uniforms.uVideoAspect.value = v.videoWidth / v.videoHeight;
    this._pushAudio();
  }

  _pushAudio() {
    this.audio.tvVolume = this.volume / 20;
    this.audio.muted = this.muted;
    for (const { video } of this.videos.values()) video.volume = this.muted ? 0 : this.volume / 20;
  }

  // ------------------------------------------------------------ per-frame
  update(dt, t) {
    const u = this.uniforms;
    const fx = this.fx;
    const signal = this.hasSignal;

    // transient effects settle back to a stable picture
    fx.kick = damp(fx.kick, 0, 3.2, dt);
    fx.glitch = damp(fx.glitch, 0.1, 2.4, dt);
    fx.roll = damp(fx.roll, 0, 4.2, dt);
    fx.band = damp(fx.band, 0, 1.6, dt);

    // occasional analog misbehaviour
    fx.nextEvent -= dt;
    if (fx.nextEvent <= 0 && this.power) {
      const r = Math.random();
      if (r < 0.45) fx.band = 1;
      else if (r < 0.75) fx.glitch = Math.max(fx.glitch, 0.55);
      else fx.roll = (Math.random() - 0.5) * 0.12;
      fx.nextEvent = 5 + Math.random() * 9;
    }

    const base = signal ? 0.035 : 0.93;
    u.uStatic.value = Math.min(1, base + fx.kick);
    u.uHasVideo.value = signal ? 1 : 0;
    u.uGlitch.value = fx.glitch;
    u.uRoll.value = fx.roll;
    u.uBand.value = fx.band;
    u.uTime.value = t;
    this.hover = damp(this.hover, this._hoverTarget ?? 0, 6, dt);
    u.uBright.value = 1 + this.hover * 0.22;
    if (signal && this.current.video.videoWidth) u.uVideoAspect.value = this.current.video.videoWidth / this.current.video.videoHeight;

    this.audio.setStatic(this.power ? Math.min(1, (signal ? 0.03 : 0.55) + fx.kick * 0.6) : 0);

    this._drawOSD(signal);

    const r = this.renderer;
    const prev = r.getRenderTarget();
    r.setRenderTarget(this.rt);
    r.render(this.quad, this.quadCam);
    if ((this._frame++ & 1) === 0) {
      r.setRenderTarget(this.probeRT);
      r.render(this.probe, this.quadCam);
      r.readRenderTargetPixels(this.probeRT, 0, 0, 1, 1, this.probePx);
      const p = this.probePx;
      this._target.setRGB(p[0] / 255, p[1] / 255, p[2] / 255, THREE.LinearSRGBColorSpace);
    }
    r.setRenderTarget(prev);

    // fast attack, slower release — flashes read as flashes
    const lum = this._target.r * 0.2126 + this._target.g * 0.7152 + this._target.b * 0.0722;
    this.lightLevel = damp(this.lightLevel, lum, lum > this.lightLevel ? 18 : 6, dt);

    // ABL: a mostly-white picture drives the beam down (the probe sees the limited
    // picture, so undo the current gain to estimate the raw average level)
    const apl = lum / Math.max(u.uGain.value, 0.3);
    const gain = 1 / (1 + Math.max(0, apl - 0.2) * 1.8);
    u.uGain.value = damp(u.uGain.value, gain, 9, dt);
    const m = Math.max(this._target.r, this._target.g, this._target.b, 1e-4);
    this.lightColor.r = damp(this.lightColor.r, this._target.r / m, 8, dt);
    this.lightColor.g = damp(this.lightColor.g, this._target.g / m, 8, dt);
    this.lightColor.b = damp(this.lightColor.b, this._target.b / m, 8, dt);
  }

  setHover(on) { this._hoverTarget = on ? 1 : 0; }

  _drawOSD(signal) {
    const now = performance.now();
    const s = this.osdState;
    const ch = this.channel;
    const noSig = this.power && !signal;
    const blink = Math.floor(now / 700) % 3 !== 2;
    const showCh = this.power && now < s.chUntil;
    const showVol = this.power && now < s.volUntil;
    const showMsg = this.power && now < s.msgUntil;
    const showInfo = this.power && now < s.infoUntil;
    const sig = [this.power, noSig && blink, showCh && ch, showVol && this.volume, this.muted && this.power, showMsg && s.msg, showInfo].join('|');
    if (sig === this.osdSig) return;
    this.osdSig = sig;

    const c = this.osdCtx;
    c.clearRect(0, 0, OSD_W, OSD_H);
    if (!this.power) { this.osdTex.needsUpdate = true; return; }
    const green = '#63ff7e';
    const text = (str, x, y, size, color = green, align = 'left') => {
      c.font = `${size}px VT323, "Courier New", monospace`;
      c.textAlign = align;
      c.textBaseline = 'top';
      c.fillStyle = 'rgba(0,0,0,0.85)';
      c.fillText(str, x + size * 0.06, y + size * 0.06);
      c.fillStyle = color;
      c.fillText(str, x, y);
    };

    if (noSig) {
      if (blink) {
        c.fillStyle = 'rgba(8, 10, 60, 0.78)';
        c.fillRect(OSD_W / 2 - 360, OSD_H / 2 - 70, 720, 140);
        text('TIDAK ADA SINYAL', OSD_W / 2, OSD_H / 2 - 48, 100, '#f2f2f2', 'center');
      }
      text(ch === 0 ? 'VIDEO 1' : `CH ${String(ch).padStart(2, '0')}`, 96, 84, 64, '#f2f2f2');
    }
    if (showCh && !(noSig && !showInfo)) {
      text(ch === 0 ? 'VIDEO 1' : `CH ${String(ch).padStart(2, '0')}`, OSD_W - 96, 80, 110, green, 'right');
    }
    if (showInfo || (showCh && signal)) {
      const name = this.videos.get(ch)?.ch.name;
      if (name && showInfo) text(name, OSD_W - 96, 196, 52, green, 'right');
    }
    if (showVol) {
      const y = OSD_H - 190;
      text('SUARA', 110, y - 70, 60);
      for (let i = 0; i < 20; i++) {
        c.fillStyle = i < this.volume ? green : 'rgba(99,255,126,0.18)';
        c.fillRect(110 + i * 40, y, 28, 56);
      }
    }
    if (this.muted) text('SUARA MATI', OSD_W - 96, OSD_H - 170, 64, green, 'right');
    if (showMsg) text(s.msg, OSD_W / 2, OSD_H - 170, 64, green, 'center');
    this.osdTex.needsUpdate = true;
  }
}
